CREATE TABLE Downloads
(
	Id UUID PRIMARY KEY,
	CreatedAt TIMESTAMP NOT NULL,
	UpdatedAt TIMESTAMP NOT NULL,
	ProjectId UUID NOT NULL REFERENCES Projects ON DELETE CASCADE,
	AccountId UUID REFERENCES Accounts ON DELETE SET NULL,

	UNIQUE NULLS DISTINCT (ProjectId, AccountId)
);