CREATE TABLE Projects 
(
	Id UUID PRIMARY KEY,
	CreatedAt TIMESTAMP NOT NULL,
	UpdatedAt TIMESTAMP NOT NULL,
	ReleasedAt TIMESTAMP NOT NULL,
	AccountId UUID NOT NULL REFERENCES Accounts,
	Name VARCHAR(80) NOT NULL,
	Slug VARCHAR(100) NOT NULL,
	Description TEXT NOT NULL,
	IsPinned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE Images
(
	Id UUID PRIMARY KEY,
	CreatedAt TIMESTAMP NOT NULL,
	UpdatedAt TIMESTAMP NOT NULL,
	Path VARCHAR(255) NOT NULL,
	Title VARCHAR(80)
);

CREATE TABLE ProjectImages
(
	Id UUID PRIMARY KEY,
	ProjectId UUID NOT NULL REFERENCES Projects,
	ImageId UUID NOT NULL REFERENCES Images,
	ImageOrder SMALLINT
);

CREATE TABLE Tags
(
	Id UUID PRIMARY KEY,
	CreatedAt TIMESTAMP NOT NULL,
	UpdatedAt TIMESTAMP NOT NULL,
	Tag TEXT NOT NULL
);

CREATE TABLE ProjectTags
(
	Id UUID PRIMARY KEY,
	ProjectId UUID NOT NULL REFERENCES Projects,
	TagId UUID NOT NULL REFERENCES Tags
);