CREATE TABLE Posts
(
	Id UUID PRIMARY KEY,
	CreatedAt TIMESTAMP NOT NULL,
	UpdatedAt TIMESTAMP NOT NULL,
	AccountId UUID NOT NULL REFERENCES Accounts,
	ProjectId UUID REFERENCES Projects,
	Title VARCHAR(80) NOT NULL,
	Content TEXT NOT NULL,
	ImageId UUID REFERENCES Images
);