DELETE FROM ProjectImages;
DELETE FROM Resources;
ALTER TABLE Resources DROP COLUMN Path;
ALTER TABLE Resources ADD AccountId UUID NOT NULL REFERENCES Accounts;
ALTER TABLE Resources ADD Path VARCHAR(255) NOT NULL;